# Generated by Django 5.0.2 on 2024-02-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='isSender',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
