# Generated by Django 5.0.2 on 2024-02-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_message_issender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='phoneId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
