# Generated by Django 5.0.2 on 2024-03-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_order_shop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produsts',
            new_name='Products',
        ),
    ]
