// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOnif5fC5xG1DybDu-u79r59g4A6MoPBI',
    appId: '1:1089468376419:web:6ee8edd7a5a63a4dbedf56',
    messagingSenderId: '1089468376419',
    projectId: 'e-commerce-3acd6',
    authDomain: 'e-commerce-3acd6.firebaseapp.com',
    storageBucket: 'e-commerce-3acd6.appspot.com',
    measurementId: 'G-X8GKCYN5B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrUZgTVnmyIk9GspYwjlxfOp7wQ9PIYjQ',
    appId: '1:1089468376419:android:a778d60c64bc7058bedf56',
    messagingSenderId: '1089468376419',
    projectId: 'e-commerce-3acd6',
    storageBucket: 'e-commerce-3acd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnsWlAjn83bKKHrdfK1iycs1-hrgbYEaE',
    appId: '1:1089468376419:ios:c0e85c6175a2fc8ebedf56',
    messagingSenderId: '1089468376419',
    projectId: 'e-commerce-3acd6',
    storageBucket: 'e-commerce-3acd6.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnsWlAjn83bKKHrdfK1iycs1-hrgbYEaE',
    appId: '1:1089468376419:ios:53775f7e754aca29bedf56',
    messagingSenderId: '1089468376419',
    projectId: 'e-commerce-3acd6',
    storageBucket: 'e-commerce-3acd6.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
